on:
  push:
name: action
jobs:
  hello-world:
    name: un job para saludar
    runs-on: ubuntu-latest
    steps:
      - name: Step Hola Mundo
        id: hello
        uses: S3bastianCruz/AhoraSi@v2
        with:
          who-to-greet: "colaboradore BdB"
      - name: Usar el output
        run: echo "La fecha fue ${{ steps.hello.outputs.time}}"
